# Generated by Django 3.2.6 on 2021-08-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_airticle_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='airticle',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
